/**
 * Generates `public/sitemap-devices.xml` from the device taxonomy.
 * Run via: `npx tsx scripts/generate-device-sitemap.ts`
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { enumerateAllRoutes, pillars, clusters } from "../src/lib/deviceTaxonomy";

const SITE = "https://mallelbostan.com";
const TODAY = new Date().toISOString().slice(0, 10);

function priorityFor(route: string): string {
  const depth = route.split("/").filter(Boolean).length; // /devices/{p}/{c}/{lt}
  if (depth === 2) return "0.8"; // pillar
  if (depth === 3) return "0.65"; // cluster
  return "0.5"; // long-tail
}

function changefreqFor(route: string): string {
  const depth = route.split("/").filter(Boolean).length;
  if (depth === 2) return "weekly";
  if (depth === 3) return "weekly";
  return "monthly";
}

const routes = enumerateAllRoutes();

const urls = routes
  .map(
    (r) => `  <url>
    <loc>${SITE}${r}</loc>
    <lastmod>${TODAY}</lastmod>
    <changefreq>${changefreqFor(r)}</changefreq>
    <priority>${priorityFor(r)}</priority>
  </url>`,
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/generate-device-sitemap.ts — do not edit manually -->
<!-- Pillars: ${pillars.length} | Clusters: ${clusters.length} | Total: ${routes.length} -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

const outPath = resolve(process.cwd(), "public/sitemap-devices.xml");
writeFileSync(outPath, xml, "utf8");
console.log(`✓ Wrote ${routes.length} URLs to ${outPath}`);
